version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/go.zenithar.org/piid
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/go.zenithar.org/piid/bin
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "tools/go.sum" }}

      - run: |
          go run mage.go docker:build     

      - save_cache:
          key: go-mod-v1-{{ checksum "tools/go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
