version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          DOCKER_BUILDKIT: 1
    working_directory: /go/src/go.zenithar.org/piid
    environment:
      GOBIN: /go/src/go.zenithar.org/piid/bin
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: |
          go run mage.go docker:build     

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
