version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          DOCKER_BUILDKIT: 1
    working_directory: /go/src/go.zenithar.org/piid
    environment:
      GOBIN: /go/src/go.zenithar.org/piid/bin
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          go run mage.go docker:build     

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
